persistence: 
  enabled: true 
  size: 2Gi
initChownData:
  enabled: false
ingress:
  enabled: true
  path: /
  hosts:
    - grafana.corp.local
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lab-ca-issuer
  pathType: Prefix
  tls:
  - hosts: 
    - grafana.corp.local
    secretName: grafana-secret
