apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app: metrics-server
spec:
  project: prod
  source:
    repoURL: 'http://gitea-prod-http.prod.svc.cluster.local:3000/corp/infra-repo.git'
    path: charts/metrics-server
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - prod-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 3
      backoff:
        duration: 5s
